### ISSUE TITLE
密码

### ISSUE THREAD

**Issue by widekk** [lixaviers/xavier-pms#3]
你不给密码怎么搞

**Comment by Pengyuyanme** [comment]
我把他的代码加密部分给弄出来了，然后给你个加密后的密码直接替代数据库密码$2a$10$PgioaaJ2nLyce.S9DK7TNeQirfhmoJSmOJKu74SzGBv8OXLDjDbq6    这个是12345加密后的密码

**Comment by lixaviers** [comment]
前端登录页是有用户名和密码的，直接登录就可以了，或者看下前端页面：https://github.com/lixaviers/xavier-pms/blob/main/xavier-pms-ui/src/views/login.vue
